# Generated by Django 3.2.18 on 2023-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_app', '0001_create_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Personal', 'Personal'), ('Business', 'Business')], max_length=12),
        ),
    ]
